'use strict';const $=id=>document.getElementById(id);let BASE=[],P=[],selected=null;const STORE='shimosuwa_place_management_edits_v1';const flags=['朝食向き','おやつ向き','昼食向き','夕食向き','休憩向き','観光向き','買い物向き','雨の日向き','子ども向き','高齢者向き','一人向き','短時間立寄り向き'];const editable=['名称','種別','カテゴリ','サブカテゴリ','住所','latitude','longitude','営業日','営業時間','定休日','おすすめ度','自動提案','おすすめ時間帯','対象','除外条件','公開メモ','運営メモ','体験・できること','最短滞在時間_分','推奨滞在時間_分','最大滞在時間_分','屋内外','徒歩アクセス難易度','坂道','トイレ','多目的トイレ','座れる場所','車椅子対応','駐車場','最寄りバス停','情報源_web','確認ステータス'];
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function loadEdits(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch(e){return{}}}function saveEdits(o){localStorage.setItem(STORE,JSON.stringify(o))}function key(p){return PlaceData.keyOf(p)}
function applyLocal(){const e=loadEdits();P=BASE.map(p=>({...p,...(e[key(p)]||{})}))}
function effective(p,n){const o=p[n+'_override'];return o!==undefined&&o!==''?o:(p[n]??'')}
function isTourism(p){const t=[p['種別'],p['カテゴリ'],p['サブカテゴリ']].join(' ');return PlaceData.truthy(effective(p,'観光向き'))||/観光|神社|寺院|史跡|博物館|美術館|景勝|公園|温泉|自然|文化/.test(t)}
function renderList(){const q=$('q').value.toLowerCase(),f=$('filter').value;let rows=P.filter(p=>{const txt=[p['名称'],p['種別'],p['カテゴリ'],p['住所']].join(' ').toLowerCase();if(q&&!txt.includes(q))return false;if(f==='coords'&&PlaceData.hasCoord(p))return false;if(f==='conditional'&&!['conditional','hidden'].includes(PlaceData.autoLevel(p)))return false;if(f==='unverified'&&!/要|未|unknown/i.test([p['確認ステータス'],p['web確認ステータス'],p['座標ステータス']].join(' ')))return false;if(f==='restaurant'&&p['種別']!=='飲食店')return false;if(f==='landmark'&&!isTourism(p))return false;return true});$('count').textContent=`${rows.length}件 / 全${P.length}件`;$('list').innerHTML=rows.map(p=>`<div class="item ${selected===key(p)?'sel':''}" onclick="selectPlace('${esc(key(p)).replace(/'/g,'&#39;')}')"><b>${esc(p['名称'])}</b><div class="sm">${esc(p['種別']||'')} / ${esc(p['カテゴリ']||'')}</div><div class="badges"><span class="badge ${PlaceData.recommendation(p)>=4?'good':''}">おすすめ ${PlaceData.recommendation(p)}/5</span><span class="badge ${PlaceData.autoLevel(p)==='conditional'||PlaceData.autoLevel(p)==='hidden'?'warn':''}">${esc(PlaceData.autoLevel(p))}</span>${!PlaceData.hasCoord(p)?'<span class="badge warn">座標なし</span>':''}</div></div>`).join('')}
function selectPlace(k){selected=k;const p=P.find(x=>key(x)===k);if(!p)return;$('empty').style.display='none';$('editor').style.display='block';$('title').textContent=p['名称'];$('idline').textContent=(p.place_id||'')+' / '+(p['種別']||'');for(const n of editable){const e=$(n);if(!e)continue;e.value=['営業日','営業時間','定休日'].includes(n)?effective(p,n):(p[n]??'')}renderFlags(p);$('saveState').textContent='';renderList()}
function renderFlags(p){$('flags').innerHTML=flags.map(n=>{const v=effective(p,n);return `<div class="flag"><label>${n}</label><select id="flag_${n}"><option value="">unknown</option><option value="yes" ${PlaceData.truthy(v)?'selected':''}>yes</option><option value="no" ${PlaceData.no(v)?'selected':''}>no</option></select></div>`}).join('')}
function gather(){const p=P.find(x=>key(x)===selected);if(!p)return null;const out={};for(const n of editable){const e=$(n);if(e)out[n]=e.value.trim()}for(const n of flags)out[n+'_override']=$('flag_'+n).value;out['営業日_override']=$('営業日').value.trim();out['営業時間_override']=$('営業時間').value.trim();out['定休日_override']=$('定休日').value.trim();out['最短滞在時間_分_override']=$('最短滞在時間_分').value.trim();out['推奨滞在時間_分_override']=$('推奨滞在時間_分').value.trim();out['最大滞在時間_分_override']=$('最大滞在時間_分').value.trim();out['管理更新日']=new Date().toISOString().slice(0,10);return out}
function saveCurrent(){if(!selected)return;const edits=loadEdits(),g=gather();edits[selected]={...(edits[selected]||{}),...g};saveEdits(edits);applyLocal();$('saveState').innerHTML='<span class="unsaved">ブラウザ保存済み・GitHub未反映</span>';selectPlace(selected)}function resetCurrent(){if(!selected)return;const e=loadEdits();delete e[selected];saveEdits(e);applyLocal();selectPlace(selected)}function clearLocal(){if(!confirm('このブラウザに保存した全変更を破棄しますか？'))return;localStorage.removeItem(STORE);applyLocal();selected=null;$('editor').style.display='none';$('empty').style.display='block';renderList()}
function managementRows(){const edits=loadEdits();return P.map(p=>{const k=key(p),e=edits[k]||{};const r={place_id:p.place_id||'',名称:p['名称']||'',おすすめ度:e['おすすめ度']??p['おすすめ度']??'3',自動提案:e['自動提案']??p['自動提案']??'normal',おすすめ用途:e['おすすめ用途']??p['おすすめ用途']??'',おすすめ時間帯:e['おすすめ時間帯']??p['おすすめ時間帯']??'',対象:e['対象']??p['対象']??'',除外条件:e['除外条件']??p['除外条件']??'',公開メモ:e['公開メモ']??p['公開メモ']??'',運営メモ:e['運営メモ']??p['運営メモ']??'',管理更新日:e['管理更新日']??p['管理更新日']??''};for(const n of flags)r[n+'_override']=e[n+'_override']??p[n+'_override']??'';for(const n of ['営業日','営業時間','定休日','最短滞在時間_分','推奨滞在時間_分','最大滞在時間_分'])r[n+'_override']=e[n+'_override']??p[n+'_override']??'';return r})}
function exportManagement(){if(selected)saveCurrent();const csv=PlaceData.toCSV(managementRows(),PlaceData.managementHeaders()),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='place_management.csv';a.click();URL.revokeObjectURL(a.href)}
function purposeMatch(p,t){const c=[p['種別'],p['カテゴリ'],p['サブカテゴリ'],p['料理ジャンル'],p['提供メニュータグ']].join(' '),yn=n=>PlaceData.truthy(effective(p,n));if(t==='landmark')return yn('観光向き')||(/神社|寺院|史跡|博物館|美術館|景勝|公園|温泉|自然|文化/.test(c)&&!/コンビニ|行政|医療|生活サービス/.test(c));if(t==='lunch')return yn('昼食向き')||p['種別']==='飲食店';if(t==='snack')return yn('おやつ向き')||/カフェ|喫茶|パン|ベーカリー|菓子|ケーキ/.test(c);if(t==='onsen')return /温泉|足湯/.test(c);if(t==='cafe')return /カフェ|喫茶/.test(c);if(t==='park')return /公園|自然|散歩|湖畔/.test(c);if(t==='rest')return yn('休憩向き')||/休憩|公園|カフェ|温泉/.test(c);return false}
function dayOK(p,w){const closed=effective(p,'定休日'),days=effective(p,'営業日');if(String(closed).includes(w))return false;if(!days||days==='毎日')return true;if(days==='平日')return !['土','日'].includes(w);return String(days).includes(w)}function timeOK(p,w,time){if(!dayOK(p,w))return false;const [hh,mm]=time.split(':').map(Number),t=hh*60+mm,s=String(effective(p,'営業時間')||'');if(!s||s.includes('24時間'))return true;const ranges=[...s.matchAll(/(\d{1,2}):(\d{2})\s*(?:-|〜|～)\s*(\d{1,2}):(\d{2})/g)];if(!ranges.length)return true;return ranges.some(x=>{let a=+x[1]*60+ +x[2],b=+x[3]*60+ +x[4];if(b===0)b=1440;return t>=a&&t<=b})}
function testPlace(){const p={...P.find(x=>key(x)===selected),...gather()},purpose=$('testPurpose').value,w=$('testDay').value,time=$('testTime').value,reasons=[];let ok=true;if(PlaceData.autoLevel(p)==='hidden'){ok=false;reasons.push('自動提案が「原則出さない」')}else if(PlaceData.autoLevel(p)==='conditional')reasons.push('条件付きPlace');if(!purposeMatch(p,purpose)){ok=false;reasons.push('用途属性が一致しない')}if(!PlaceData.hasCoord(p)){ok=false;reasons.push('座標が未設定')}if(!dayOK(p,w)){ok=false;reasons.push(w+'曜日は営業対象外')}else if(!timeOK(p,w,time)){ok=false;reasons.push(time+'は営業時間外')}reasons.push('おすすめ度 '+PlaceData.recommendation(p)+'/5');const r=$('testResult');r.className='result '+(ok?'ok':'ng');r.textContent=(ok?'候補にできます：':'候補から除外：')+reasons.join(' / ')}
$('q').oninput=renderList;$('filter').onchange=renderList;async function init(){const {places}=await PlaceData.loadAll();BASE=places;applyLocal();renderList()}init();