'use strict';
const $=id=>document.getElementById(id);let P=[],B=[],A=[],W=[],seq=0,pick=null,pt={s:null,g:null},mk={s:null,g:null},route=null;
const map=L.map('map').setView([36.075,138.083],14);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
const D={snack:['🍰 おやつ',30],lunch:['🍽️ 昼食',50],landmark:['⛩️ 観光',40],onsen:['♨️ 温泉',50],cafe:['☕ カフェ',40],park:['🌳 公園・散歩',40],rest:['🪑 休憩',20],free:['⏳ 自由時間',30]};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setPoint(k,p){pt[k]={name:p.name,lat:+p.lat,lng:+p.lng};$(k+'c').textContent=p.name+' / '+p.lat.toFixed(6)+', '+p.lng.toFixed(6);if(mk[k])map.removeLayer(mk[k]);mk[k]=L.marker([p.lat,p.lng]).addTo(map).bindPopup(k==='s'?'START':'GOAL').openPopup();map.setView([p.lat,p.lng],15)}
function gps(k){if(!navigator.geolocation)return alert('このブラウザでは位置情報を利用できません');navigator.geolocation.getCurrentPosition(x=>setPoint(k,{name:'現在地',lat:x.coords.latitude,lng:x.coords.longitude}),()=>alert('位置情報を取得できませんでした'))}
map.on('click',e=>{if(pick){setPoint(pick,{name:'地図で選択',lat:e.latlng.lat,lng:e.latlng.lng});pick=null}});
function text(p){return [p['種別'],p['カテゴリ'],p['サブカテゴリ'],p['体験・できること'],p['料理ジャンル'],p['提供メニュータグ']].join(' ')}
function yn(p,name){return PlaceData.truthy(PlaceData.effective(p,name))}
function match(p,t){const c=text(p);if(t==='snack')return yn(p,'おやつ向き')||/カフェ|喫茶|ベーカリー|パン|菓子|ケーキ|軽食/.test(c);if(t==='lunch')return yn(p,'昼食向き')||p['種別']==='飲食店';if(t==='cafe')return /カフェ|喫茶/.test(c);if(t==='onsen')return /温泉|足湯/.test(c);if(t==='park')return /公園|自然|湖畔|散歩/.test(c);if(t==='rest')return yn(p,'休憩向き')||/休憩|公園|カフェ|温泉/.test(c);if(t==='landmark'){if(yn(p,'観光向き'))return true;if(PlaceData.no(PlaceData.effective(p,'観光向き')))return false;return /神社|寺院|史跡|博物館|美術館|景勝|公園|温泉|文化|自然|観光/.test(c)&&!/コンビニ|スーパー|行政|医療|公衆トイレ|駐車場|レンタサイクル|生活サービス/.test(c);}return false}
function autoAllowed(p,explicit=false){const lv=PlaceData.autoLevel(p);if(explicit)return lv!=='hidden';if(lv==='hidden')return false;if(lv==='conditional'&&!$('allowConditional').checked)return false;return true}
function candidateBase(t){return P.filter(p=>match(p,t)&&autoAllowed(p,false))}
function addWish(t,o={}){W.push({id:++seq,t,d:o.d||D[t][1],time:o.time||'',pid:o.pid||''});renderWishes()}
function delWish(id){W=W.filter(w=>w.id!==id);renderWishes()}
function moveWish(id,n){const i=W.findIndex(w=>w.id===id),j=i+n;if(i<0||j<0||j>=W.length)return;[W[i],W[j]]=[W[j],W[i]];renderWishes()}
function changeWish(id,k,v){const w=W.find(w=>w.id===id);if(!w)return;w[k]=v;if(k==='t'){w.d=D[v][1];w.pid='';renderWishes()}}
function renderWishes(){$('wc').textContent=W.length+'ブロック';$('wl').innerHTML=W.map((w,i)=>{const C=candidateBase(w.t).filter(PlaceData.hasCoord);const opts='<option value="">場所もおまかせ</option>'+C.map(p=>`<option value="${esc(PlaceData.keyOf(p))}" ${w.pid===PlaceData.keyOf(p)?'selected':''}>${esc(p['名称'])} ★${PlaceData.recommendation(p)}</option>`).join('');return `<div class="wish"><div class="num">${i+1}</div><div class="wide"><label>内容</label><select onchange="changeWish(${w.id},'t',this.value)">${Object.entries(D).map(([k,v])=>`<option value="${k}" ${k===w.t?'selected':''}>${v[0]}</option>`).join('')}</select></div><div><label>希望時刻</label><input type="time" value="${w.time}" onchange="changeWish(${w.id},'time',this.value)"></div><div><label>滞在</label><select onchange="changeWish(${w.id},'d',+this.value)">${[15,20,30,40,50,60,90].map(n=>`<option ${n===+w.d?'selected':''}>${n}分</option>`).join('')}</select></div><div class="wide"><label>場所</label><select onchange="changeWish(${w.id},'pid',this.value)">${opts}</select><div class="sm">座標あり候補 ${C.length}件</div></div><div class="ctrl"><button class="alt" onclick="moveWish(${w.id},-1)">↑</button><button class="alt" onclick="moveWish(${w.id},1)">↓</button><button class="alt" onclick="delWish(${w.id})">削除</button></div></div>`}).join('')}
function sample(){W=[];seq=0;addWish('snack',{time:'10:00'});addWish('landmark');addWish('lunch',{time:'12:00'});addWish('onsen');addWish('snack',{time:'15:00'})}
function min(s){if(!s)return null;const [a,b]=s.split(':').map(Number);return a*60+b}function fmt(n){return String(Math.floor(n/60)%24).padStart(2,'0')+':'+String(Math.round(n)%60).padStart(2,'0')}
function dist(a,b){const R=6371,r=x=>x*Math.PI/180,dp=r(b.lat-a.lat),dl=r(b.lng-a.lng),q=Math.sin(dp/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(q))}function walk(a,b){return Math.max(2,Math.round(dist(a,b)/4*60*1.18))}
function dayOK(p){const w=$('wd').value,closed=PlaceData.effective(p,'定休日'),days=PlaceData.effective(p,'営業日');if(String(closed).includes(w))return false;if(!days||days==='毎日')return true;if(days==='平日')return !['土','日'].includes(w);return String(days).includes(w)}
function timeOK(p,t){if(!dayOK(p))return false;const s=String(PlaceData.effective(p,'営業時間')||'');if(!s||s.includes('24時間'))return true;const ranges=[...s.matchAll(/(\d{1,2}):(\d{2})\s*(?:-|〜|～)\s*(\d{1,2}):(\d{2})/g)];if(!ranges.length)return true;return ranges.some(x=>{let a=+x[1]*60+ +x[2],b=+x[3]*60+ +x[4];if(b===0)b=1440;return t>=a&&t<=b})}
function diagnostics(t,time){const all=P.filter(p=>match(p,t)&&autoAllowed(p,false)),coords=all.filter(PlaceData.hasCoord),days=coords.filter(dayOK),opens=days.filter(p=>timeOK(p,time));return{all:all.length,coords:coords.length,days:days.length,opens:opens.length}}
function score(p,from,goal){let s=PlaceData.recommendation(p)*12;const d1=walk(from,{lat:PlaceData.lat(p),lng:PlaceData.lng(p)}),d2=walk({lat:PlaceData.lat(p),lng:PlaceData.lng(p)},goal);s-=d1+d2*.2;if($('rain').checked&&yn(p,'雨の日向き'))s+=12;if($('senior').checked&&yn(p,'高齢者向き'))s+=12;if($('policy').value==='recommended')s+=PlaceData.recommendation(p)*10;if($('policy').value==='near')s-=d1*1.5;if(PlaceData.autoLevel(p)==='promote')s+=12;if(PlaceData.autoLevel(p)==='conditional')s-=8;return s}
function choose(w,from,goal,t,used,random){if(w.pid){const p=P.find(x=>PlaceData.keyOf(x)===w.pid);return p&&PlaceData.hasCoord(p)&&autoAllowed(p,true)&&timeOK(p,t)?p:null}const c=candidateBase(w.t).filter(p=>PlaceData.hasCoord(p)&&!used.has(PlaceData.keyOf(p))&&timeOK(p,t));if(!c.length)return null;const ranked=c.map(p=>({p,s:score(p,from,goal)})).sort((a,b)=>b.s-a.s);const top=ranked.slice(0,Math.min(5,ranked.length));return random?top[Math.floor(Math.random()*top.length)].p:top[0].p}
function nearBus(q){let z=null;for(const b of B){const p={lat:+(b.latitude||b.lat),lng:+(b.longitude||b.lng)};if(!p.lat)continue;const d=dist(q,p);if(!z||d<z.d)z={b,d}}return z&&z.d<=.45?`<span class="tag">🚌 ${esc(z.b.stop_name||z.b.name||'バス停')} 約${Math.round(z.d*1000)}m</span>`:''}
function plan(random=false){if(!pt.s||!pt.g)return alert('STARTとGOALを設定してください');let t=min($('st').value),end=min($('et').value),cur={...pt.s},used=new Set(),items=[['place',t,t,cur.name,'START',null]],warnings=[];for(const w of W){if(w.t==='free'){items.push(['free',t,t+w.d,'自由時間',w.d+'分',null]);t+=w.d;continue}const pref=min(w.time),candidateTime=pref!==null?pref:t;const p=choose(w,cur,pt.g,candidateTime,used,random);if(!p){const d=diagnostics(w.t,candidateTime);items.push(['warn',t,t+10,D[w.t][0]+'：候補なし',`全候補 ${d.all} / 座標あり ${d.coords} / ${$('wd').value}曜適合 ${d.days} / 時刻適合 ${d.opens}`,null]);warnings.push(D[w.t][0]);t+=10;continue}const q={name:p['名称'],lat:PlaceData.lat(p),lng:PlaceData.lng(p)},m=walk(cur,q);if(pref!==null&&pref>t+m){const leave=pref-m;if(leave>t)items.push(['free',t,leave,'自由時間・余白','希望時刻に到着するまで',null]);t=leave}items.push(['travel',t,t+m,'徒歩 約'+m+'分',cur.name+' → '+q.name,null]);t+=m;if(pref!==null&&t<pref){items.push(['free',t,pref,'到着待ち・余白','希望時刻まで',null]);t=pref}items.push(['act',t,t+w.d,p['名称'],`${D[w.t][0]} / ${p['カテゴリ']||p['種別']||''} / おすすめ ${PlaceData.recommendation(p)}/5`,p]);t+=w.d;used.add(PlaceData.keyOf(p));cur=q}const m=walk(cur,pt.g);items.push(['travel',t,t+m,'徒歩 約'+m+'分',cur.name+' → '+pt.g.name,null]);t+=m;if(t<end){items.push(['free',t,end,'余裕時間','GOALまで '+(end-t)+'分の余裕',null]);t=end}items.push([t>end?'warn':'place',end,end,pt.g.name,t>end?'GOAL 約'+(t-end)+'分超過':'GOAL',null]);$('ps').textContent=t>end?'時間超過':warnings.length?'一部候補不足':'成立';$('summary').innerHTML=`<span class="pill">${$('wd').value}曜日</span><span class="pill">${fmt(min($('st').value))} → ${fmt(end)}</span><span class="pill">希望 ${W.length}件</span>`;$('result').innerHTML=items.map(x=>`<div class="card ${x[0]==='travel'?'travel':''} ${x[0]==='warn'?'warn':''}"><div class="time">${x[1]===x[2]?fmt(x[1]):fmt(x[1])+'–'+fmt(x[2])}</div><div><div class="name">${esc(x[3])}</div><div class="meta">${esc(x[4])}</div>${x[5]?`<span class="star">★${PlaceData.recommendation(x[5])}</span> `+nearBus({lat:PlaceData.lat(x[5]),lng:PlaceData.lng(x[5])}):''}</div></div>`).join('');if(route)map.removeLayer(route);const pts=[pt.s,...items.filter(x=>x[5]).map(x=>({lat:PlaceData.lat(x[5]),lng:PlaceData.lng(x[5])})),pt.g];route=L.polyline(pts.map(x=>[x.lat,x.lng]),{weight:4,opacity:.65}).addTo(map);map.fitBounds(route.getBounds().pad(.15))}
async function loadTransit(){try{const r=await fetch('data/bus_stops_corrected.json?v='+Date.now(),{cache:'no-store'}),j=r.ok?await r.json():[];return Array.isArray(j)?j:(j.items||j.stops||[])}catch(e){return[]}}
async function init(){try{const [{places},bus]=await Promise.all([PlaceData.loadAll(),loadTransit()]);P=places;B=bus;A=P.filter(PlaceData.hasCoord).map(p=>({name:p['名称'],lat:PlaceData.lat(p),lng:PlaceData.lng(p),kind:p['種別'],key:PlaceData.keyOf(p)})).concat(B.map(b=>({name:b.stop_name||b.name,lat:+(b.latitude||b.lat),lng:+(b.longitude||b.lng),kind:(b.bus_system||'バス')+' バス停'})).filter(x=>x.lat));for(const [id,k] of [['ss','s'],['gs','g']]){const e=$(id);e.innerHTML='<option value="">登録地点から選ぶ</option>'+A.map((p,i)=>`<option value="${i}">${esc(p.name)} — ${esc(p.kind||'Place')}</option>`).join('');e.onchange=()=>{if(e.value!=='')setPoint(k,A[+e.value])}}P.filter(PlaceData.hasCoord).forEach(p=>L.circleMarker([PlaceData.lat(p),PlaceData.lng(p)],{radius:p['種別']==='交通'?8:6,weight:1,fillOpacity:.55}).addTo(map).bindPopup(`<b>${esc(p['名称'])}</b><br>${esc(p['カテゴリ']||p['種別']||'')}<br>おすすめ ${PlaceData.recommendation(p)}/5`));B.forEach(b=>{const a=+(b.latitude||b.lat),o=+(b.longitude||b.lng);if(a&&o)L.circleMarker([a,o],{radius:2.5,weight:1,opacity:.35,fillOpacity:.22}).addTo(map).bindPopup(esc(b.stop_name||b.name||'バス停'))});const stn=A.find(x=>x.name==='下諏訪駅'&&x.kind==='交通')||A.find(x=>x.name==='下諏訪駅');if(stn){$('gs').value=A.indexOf(stn);setPoint('g',stn)}$('status').textContent=`Places ${P.length}件（座標あり ${P.filter(PlaceData.hasCoord).length}件） / バス停 ${B.length}地点`;sample()}catch(e){$('status').textContent='読込エラー: '+e.message;console.error(e)}}init();