(() => {
'use strict';
const TP={mode:'walk',bikeMode:'own',lastRandom:false,gtfs:{ready:false,loading:false,stops:[],routes:new Map(),trips:new Map(),byStop:new Map(),byTrip:new Map(),calendar:new Map()}};
const MODE={walk:{label:'徒歩',icon:'🚶'},bike:{label:'自転車',icon:'🚲'},car:{label:'自動車',icon:'🚗'},bus:{label:'バス',icon:'🚌'}};
const GTFS='data/gtfs/';
const H=s=>esc(s),Q=p=>({name:p['名称'],lat:PlaceData.lat(p),lng:PlaceData.lng(p)});
function nums(v){return(String(v??'').match(/\d+(?:\.\d+)?/g)||[]).map(Number)}
function dur(w,p){if(w.d!==''&&+w.d>0)return{d:+w.d,src:'指定'};const a=nums(PlaceData.effective(p,'推奨滞在時間_分'));let d=a.length>1?(a[0]+a[1])/2:(a[0]||D[w.t]?.[1]||30);return{d:Math.max(5,Math.round(d/5)*5),src:'自動'}}
function moveApprox(mode,a,b){const km=dist(a,b);if(mode==='bike')return Math.max(2,Math.round(km/12*60*1.15));if(mode==='car')return Math.max(4,Math.round(km/28*60*1.22)+3);if(mode==='bus')return Math.max(8,Math.round(km/18*60)+10);return walk(a,b)}
function rscore(p,from,goal){const z=Q(p),direct=dist(from,goal),leg=dist(from,z),on=dist(z,goal),det=Math.max(0,leg+on-direct);let s=PlaceData.recommendation(p)*18-det*75-leg*7;if(on>direct+.15)s-=28;if($('rain').checked&&yn(p,'雨の日向き'))s+=14;if($('senior').checked&&yn(p,'高齢者向き'))s+=14;if($('policy').value==='recommended')s+=PlaceData.recommendation(p)*10;if($('policy').value==='near')s-=leg*25;if(PlaceData.autoLevel(p)==='promote')s+=12;if(PlaceData.autoLevel(p)==='conditional')s-=8;return s}
function choose4(w,from,goal,t,used,random){if(w.pid){const p=P.find(x=>PlaceData.keyOf(x)===w.pid);return p&&PlaceData.hasCoord(p)&&autoAllowed(p,true)&&timeOK(p,t)?p:null}const c=candidateBase(w.t).filter(p=>PlaceData.hasCoord(p)&&!used.has(PlaceData.keyOf(p))&&timeOK(p,t));if(!c.length)return null;const r=c.map(p=>({p,s:rscore(p,from,goal)})).sort((a,b)=>b.s-a.s).slice(0,4);return random?r[Math.floor(Math.random()*r.length)].p:r[0].p}
function tm(v){const m=String(v||'').match(/^(\d+):(\d{2})/);return m?+m[1]*60+ +m[2]:999999}
function svc(id,day){const r=TP.gtfs.calendar.get(id);if(!r)return true;const k={月:'monday',火:'tuesday',水:'wednesday',木:'thursday',金:'friday',土:'saturday',日:'sunday'}[day]||'monday';return String(r[k])==='1'}
function gtfsStatus(s){const e=$('transportStatus');if(e)e.textContent=s}
async function loadGTFS(){if(TP.gtfs.ready||TP.gtfs.loading)return;TP.gtfs.loading=true;gtfsStatus('バス時刻表を読込中…');try{async function rd(n){const r=await fetch(GTFS+n+'?v=20260830-1',{cache:'force-cache'});if(!r.ok)throw Error(n+'を取得できません');return PlaceData.parseCSV(await r.text())}const[stops,routes,trips,st,cal]=await Promise.all([rd('stops.txt'),rd('routes.txt'),rd('trips.txt'),rd('stop_times.txt'),rd('calendar.txt')]);TP.gtfs.stops=stops.filter(x=>+x.stop_lat&&+x.stop_lon);TP.gtfs.routes=new Map(routes.map(x=>[x.route_id,x]));TP.gtfs.trips=new Map(trips.map(x=>[x.trip_id,x]));TP.gtfs.calendar=new Map(cal.map(x=>[x.service_id,x]));for(const x of st){if(!TP.gtfs.byStop.has(x.stop_id))TP.gtfs.byStop.set(x.stop_id,[]);TP.gtfs.byStop.get(x.stop_id).push(x);if(!TP.gtfs.byTrip.has(x.trip_id))TP.gtfs.byTrip.set(x.trip_id,[]);TP.gtfs.byTrip.get(x.trip_id).push(x)}for(const a of TP.gtfs.byStop.values())a.sort((x,y)=>tm(x.departure_time)-tm(y.departure_time));for(const a of TP.gtfs.byTrip.values())a.sort((x,y)=>+x.stop_sequence-+y.stop_sequence);TP.gtfs.ready=true;gtfsStatus(`GTFS OK：停留所 ${TP.gtfs.stops.length} / 便 ${trips.length}`)}catch(e){gtfsStatus('GTFS読込失敗：徒歩へ切替');console.warn(e)}finally{TP.gtfs.loading=false}}
const SP=s=>({name:s.stop_name||'バス停',lat:+s.stop_lat,lng:+s.stop_lon});
function nearest(p,n=5,max=.8){return TP.gtfs.stops.map(s=>({s,d:dist(p,SP(s))})).filter(x=>x.d<=max).sort((a,b)=>a.d-b.d).slice(0,n)}
function routeName(trip){const r=TP.gtfs.routes.get(trip.route_id)||{};return[r.route_short_name,r.route_long_name].filter(Boolean).join(' ')||'バス'}
async function busLeg(from,to,start){if(!TP.gtfs.ready){await loadGTFS();if(!TP.gtfs.ready)return null}const bs=nearest(from),as=nearest(to);if(!bs.length||!as.length)return null;const ids=new Set(as.map(x=>x.s.stop_id)),dm=new Map(as.map(x=>[x.s.stop_id,x]));let best=null,day=$('wd').value;for(const b of bs){const bp=SP(b.s),wi=walk(from,bp),reach=start+wi;for(const x of TP.gtfs.byStop.get(b.s.stop_id)||[]){const dep=tm(x.departure_time);if(dep<reach)continue;if(dep>reach+90)break;const tr=TP.gtfs.trips.get(x.trip_id);if(!tr||!svc(tr.service_id,day))continue;for(const y of TP.gtfs.byTrip.get(x.trip_id)||[]){if(+y.stop_sequence<=+x.stop_sequence||!ids.has(y.stop_id))continue;const arr=tm(y.arrival_time||y.departure_time),di=dm.get(y.stop_id),ap=SP(di.s),wo=walk(ap,to),finish=arr+wo;if(!best||finish<best.finish)best={board:b.s,alight:di.s,depart:dep,arrive:arr,walkIn:wi,walkOut:wo,finish,route:routeName(tr)};break}}}return best}
function rental(){const c=P.filter(PlaceData.hasCoord).filter(p=>/レンタサイクル|今昔館おいでや|友之町駐車場/.test(p['名称']||''));if(c.length)return Q(c.map(p=>({p,d:dist(pt.s,Q(p))})).sort((a,b)=>a.d-b.d)[0].p);return{name:'しもすわ今昔館おいでや（レンタサイクル）',lat:36.0758,lng:138.08918}}
function simple(items,a,b,t,mode,suffix=''){const m=moveApprox(mode,a,b),z=MODE[mode];items.push({type:'travel',from:t,to:t+m,title:`${z.icon} ${z.label} 約${m}分`,meta:`${a.name} → ${b.name}${suffix}`});return t+m}
async function move(items,a,b,t){if(TP.mode!=='bus')return simple(items,a,b,t,TP.mode);const l=await busLeg(a,b,t);if(!l){const m=walk(a,b);items.push({type:'travel',warn:true,from:t,to:t+m,title:`🚶 徒歩 約${m}分`,meta:`直通バス便が見つからないため徒歩 / ${a.name} → ${b.name}`});return t+m}const bp=SP(l.board),ap=SP(l.alight);if(l.walkIn){items.push({type:'travel',from:t,to:t+l.walkIn,title:`🚶 バス停まで徒歩 約${l.walkIn}分`,meta:`${a.name} → ${bp.name}`});t+=l.walkIn}if(t<l.depart){items.push({type:'wait',from:t,to:l.depart,title:'バス待ち',meta:`${bp.name}で ${fmt(l.depart)} 発を待つ`});t=l.depart}items.push({type:'bus',from:l.depart,to:l.arrive,title:`🚌 ${l.route}`,meta:`${bp.name} ${fmt(l.depart)}発 → ${ap.name} ${fmt(l.arrive)}着`});t=l.arrive;if(l.walkOut){items.push({type:'travel',from:t,to:t+l.walkOut,title:`🚶 降車後 徒歩 約${l.walkOut}分`,meta:`${ap.name} → ${b.name}`});t+=l.walkOut}return t}
function nextW(rem,cur,goal,t,used,random){const fixed=rem.filter(w=>min(w.time)!==null).sort((a,b)=>min(a.time)-min(b.time));if(fixed.length&&min(fixed[0].time)<=t+45)return fixed[0];const flex=rem.filter(w=>min(w.time)===null&&w.t!=='free');if(flex.length){const r=flex.map(w=>{const p=choose4(w,cur,goal,t,used,false);return{w,p,s:p?rscore(p,cur,goal):-1e9}}).sort((a,b)=>b.s-a.s).filter(x=>x.p).slice(0,3);if(r.length)return random?r[Math.floor(Math.random()*r.length)].w:r[0].w}return fixed[0]||rem[0]}
changeWish=function(id,k,v){const w=W.find(x=>x.id===id);if(!w)return;if(k==='d')w.d=v===''?'':+v;else w[k]=v;if(k==='t'){w.d='';w.pid='';renderWishes()}};
addWish=function(t,o={}){W.push({id:++seq,t,d:o.d??'',time:o.time||'',pid:o.pid||''});renderWishes()};
renderWishes=function(){$('wc').textContent=W.length+'件';$('wl').innerHTML=W.map((w,i)=>{const auto=candidateBase(w.t).filter(PlaceData.hasCoord),manual=P.filter(p=>match(p,w.t)&&PlaceData.hasCoord(p)),opts='<option value="">場所もおまかせ</option>'+manual.map(p=>`<option value="${H(PlaceData.keyOf(p))}" ${w.pid===PlaceData.keyOf(p)?'selected':''}>${H(p['名称'])} ★${PlaceData.recommendation(p)}</option>`).join(''),op=w.time||w.d!==''?'open':'';return`<div class="wish v4-wish"><div class="num">${i+1}</div><div><label>やりたいこと</label><select onchange="changeWish(${w.id},'t',this.value)">${Object.entries(D).map(([k,v])=>`<option value="${k}" ${k===w.t?'selected':''}>${v[0]}</option>`).join('')}</select></div><div><label>場所</label><select onchange="changeWish(${w.id},'pid',this.value)">${opts}</select><div class="sm">おまかせ候補 ${auto.length}件</div></div><div class="ctrl"><button class="alt" onclick="moveWish(${w.id},-1)">↑</button><button class="alt" onclick="moveWish(${w.id},1)">↓</button><button class="alt" onclick="delWish(${w.id})">削除</button></div><details class="wish-detail" ${op}><summary>時刻・滞在を指定する（任意）</summary><div class="wish-detail-grid"><div><label>希望時刻</label><input type="time" value="${H(w.time)}" onchange="changeWish(${w.id},'time',this.value)"></div><div><label>滞在時間</label><select onchange="changeWish(${w.id},'d',this.value)"><option value="" ${w.d===''?'selected':''}>おまかせ</option>${[15,20,30,40,50,60,90,120].map(n=>`<option value="${n}" ${+w.d===n?'selected':''}>${n}分</option>`).join('')}</select></div></div></details></div>`}).join('')};
sample=function(){W=[];seq=0;addWish('snack');addWish('landmark');addWish('lunch');addWish('onsen');addWish('snack')};
function render(items,end,warns,pts){const total=items.filter(x=>x.type==='travel'||x.type==='bus').reduce((a,x)=>a+x.to-x.from,0),finish=items.length?items[items.length-1].to:end;$('ps').textContent=finish>end?'時間超過':warns.length?'一部候補不足':'成立';$('summary').innerHTML=`<span class="pill">${H($('wd').value)}曜日</span><span class="pill">${fmt(min($('st').value))} → ${fmt(end)}</span><span class="pill">${MODE[TP.mode].icon} ${MODE[TP.mode].label}</span><span class="pill">移動 約${total}分</span><span class="pill">希望 ${W.length}件</span>`;$('result').innerHTML=items.map(x=>`<div class="card ${(x.type==='travel'||x.type==='bus')?'travel':''} ${x.type==='bus'?'bus-travel':''} ${(x.warn||x.type==='warn')?'warn':''}"><div class="time">${x.from===x.to?fmt(x.from):fmt(x.from)+'–'+fmt(x.to)}</div><div><div class="name">${H(x.title)}</div><div class="meta">${H(x.meta||'')}</div>${x.point?`<span class="star">★${PlaceData.recommendation(x.point)}</span> ${nearBus({lat:PlaceData.lat(x.point),lng:PlaceData.lng(x.point)})}`:''}</div></div>`).join('');if(route)map.removeLayer(route);if(pts.length>1){route=L.polyline(pts.map(x=>[x.lat,x.lng]),{weight:4,opacity:.65}).addTo(map);map.fitBounds(route.getBounds().pad(.15))}}
plan=async function(random=false){if(!pt.s||!pt.g)return alert('STARTとGOALを設定してください');TP.lastRandom=random;if(TP.mode==='bus'&&!TP.gtfs.ready)await loadGTFS();let t=min($('st').value),end=min($('et').value),cur={...pt.s},items=[{type:'place',from:t,to:t,title:cur.name,meta:'START'}],warns=[],used=new Set(),rem=W.slice(),pts=[{...cur}],rent=null;if(TP.mode==='bike'&&TP.bikeMode==='rental'){rent=rental();t=simple(items,cur,rent,t,'walk',' / レンタサイクル受取へ');cur={...rent};pts.push({...cur});items.push({type:'act',from:t,to:t+10,title:'🚲 レンタサイクルを借りる',meta:`${rent.name} / 受取手続き 10分（試作）`});t+=10}while(rem.length){const w=nextW(rem,cur,pt.g,t,used,random);rem.splice(rem.indexOf(w),1);if(w.t==='free'){const d=+w.d||D.free[1];items.push({type:'free',from:t,to:t+d,title:'自由時間',meta:`${d}分`});t+=d;continue}const pref=min(w.time),ct=pref!==null?pref:t,p=choose4(w,cur,pt.g,ct,used,random);if(!p){const d=diagnostics(w.t,ct);items.push({type:'warn',from:t,to:t+10,title:D[w.t][0]+'：候補なし',meta:`全候補 ${d.all} / 座標あり ${d.coords} / ${$('wd').value}曜適合 ${d.days} / 時刻適合 ${d.opens}`});warns.push(D[w.t][0]);t+=10;continue}const z=Q(p),ap=moveApprox(TP.mode,cur,z);if(pref!==null&&pref>t+ap){const leave=pref-ap;if(leave>t){items.push({type:'free',from:t,to:leave,title:'余白時間',meta:'希望時刻に合わせて出発'});t=leave}}t=await move(items,cur,z,t);cur=z;pts.push({...cur});if(pref!==null&&t<pref){items.push({type:'wait',from:t,to:pref,title:'到着後の余白',meta:`希望時刻 ${fmt(pref)} まで`});t=pref}const di=dur(w,p),late=pref!==null&&t>pref+10?` / 希望 ${fmt(pref)} より約${t-pref}分遅れ`:'';items.push({type:'act',from:t,to:t+di.d,title:p['名称'],meta:`${D[w.t][0]} / ${p['カテゴリ']||p['種別']||''} / 滞在${di.d}分（${di.src}） / おすすめ ${PlaceData.recommendation(p)}/5${late}`,point:p});t+=di.d;used.add(PlaceData.keyOf(p))}if(rent){t=simple(items,cur,rent,t,'bike',' / レンタサイクル返却へ');cur={...rent};pts.push({...cur});items.push({type:'act',from:t,to:t+5,title:'🚲 レンタサイクルを返却',meta:'同じ貸出場所へ返却する試作ルール / 5分'});t+=5;t=simple(items,cur,pt.g,t,'walk');cur={...pt.g};pts.push({...cur})}else{t=await move(items,cur,pt.g,t);cur={...pt.g};pts.push({...cur})}if(t<end){items.push({type:'free',from:t,to:end,title:'余裕時間',meta:`GOALまで ${end-t}分の余裕`});t=end}items.push({type:t>end?'warn':'place',from:end,to:end,title:pt.g.name,meta:t>end?`GOAL 約${t-end}分超過`:'GOAL'});render(items,end,warns,pts)};
function setMode(m){TP.mode=m;document.querySelectorAll('[data-transport]').forEach(b=>b.classList.toggle('active',b.dataset.transport===m));$('bikeOptions').style.display=m==='bike'?'flex':'none';$('transportStatus').style.display=m==='bus'?'inline':'none';if(m==='bus')loadGTFS();if(pt.s&&pt.g&&$('result').querySelector('.card'))plan(TP.lastRandom)}
function ui(){if($('transportChooser'))return;const head=$('ps').parentElement,w=document.createElement('div');w.id='transportChooser';w.className='transport-wrap';w.innerHTML=`<span class="transport-label">移動方法</span><div class="transport-buttons">${Object.entries(MODE).map(([k,v])=>`<button type="button" data-transport="${k}" class="transport-btn ${k==='walk'?'active':''}">${v.icon} ${v.label}</button>`).join('')}</div><div id="bikeOptions" class="bike-options"><label>自転車</label><select id="bikeMode"><option value="own">自分の自転車</option><option value="rental">レンタサイクルを借りる</option></select></div><span id="transportStatus" class="sm" style="display:none">GTFS待機中</span>`;head.insertAdjacentElement('afterend',w);w.querySelectorAll('[data-transport]').forEach(b=>b.onclick=()=>setMode(b.dataset.transport));$('bikeMode').onchange=e=>{TP.bikeMode=e.target.value;if(pt.s&&pt.g)plan(TP.lastRandom)}}
function style(){const s=document.createElement('style');s.textContent=`.v4-wish{grid-template-columns:32px 1fr 1.35fr auto;align-items:end}.v4-wish .wish-detail{grid-column:2/5;border-top:1px dashed #dfe5e7;padding-top:7px}.wish-detail summary{cursor:pointer;color:#52606b;font-size:11px;font-weight:800}.wish-detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px}.transport-wrap{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:10px 0 2px;padding:10px;border:1px solid #dfe6e3;border-radius:12px;background:#f9fbfa}.transport-label{font-size:12px;font-weight:900;color:#52606b}.transport-buttons{display:flex;gap:5px;flex-wrap:wrap}.transport-btn{background:#edf1f2;color:#34434f;padding:7px 10px;font-size:12px}.transport-btn.active{background:#245e52;color:#fff;box-shadow:0 0 0 2px #cfe2dc}.bike-options{display:none;align-items:center;gap:6px}.bike-options label{margin:0}.bike-options select{width:auto;padding:7px}.bus-travel{background:#eef5ff!important;border-color:#b9d0f5!important;border-style:solid!important}@media(max-width:700px){.v4-wish{grid-template-columns:30px 1fr}.v4-wish>div:nth-child(3),.v4-wish .ctrl,.v4-wish .wish-detail{grid-column:2}.v4-wish .ctrl{justify-content:flex-end}.wish-detail-grid{grid-template-columns:1fr}.transport-label,.transport-buttons,.bike-options{width:100%}.transport-btn{flex:1 1 44%}.bike-options select{flex:1}}`;document.head.appendChild(s)}
function boot(){style();ui();renderWishes();window.TransportPlanner=TP}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
